version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: npm-user-validate
    versions:
    - 1.0.1
  - dependency-name: gherkin-lint
    versions:
    - 4.1.3
  - dependency-name: npm-registry-fetch
    versions:
    - 4.0.7
  - dependency-name: handlebars
    versions:
    - 4.7.6
