version: 2
jobs:
  lint-features:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run lint:features

  test-with-python-hooks:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dev dependencies (Node.js)
          command: npm install
      - run:
          name: Install the reference hooks implementation (Python)
          command: sudo pip install dredd_hooks
      - run:
          name: Test
          command: |
            node scripts/prepare-test.js
            export PATH=$PATH:$(pwd)/node_modules/.bin
            cd ./test
            npm test

workflows:
  version: 2
  build:
    jobs:
      - lint-features
      - test-with-python-hooks
