version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  test-with-python-hooks:
    docker:
      - image: circleci/python:3.7-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies (Node.js)
          command: npm install
      - run:
          name: Install the reference hooks implementation (Python)
          command: sudo pip install dredd_hooks
      - run:
          name: Test
          command: npm test

  release:
    # needs NPM_TOKEN and GH_TOKEN environment variables set
    # in https://circleci.com/gh/apiaryio/dredd-hooks-template/edit#env-vars
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run release

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test-with-python-hooks
      - release:
          requires:
            - lint
            - test-with-python-hooks
